hanuiproject/blog/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.conf.urls import url
from .views import search

app_name = 'blog'

urlpatterns = [
    path('<int:blog_id>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('', views.blog, name='blog'),
    path('newblog/', views.blogpost, name="newblog"),
    url(r'^results/$', search, name='search'),
    path('me/', views.me, name="me"),
    url(r'^category/$', views.get_queryset, name='category'),
]

hanuiproject/hanuiproject/urls.py
from django.contrib import admin
from django.urls import path, include
import blog.views
import accounte.views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
# django.contrib.auth.views.LoginView

admin.autodiscover()
app_name = 'blog'
urlpatterns = [
    path('', blog.views.blog),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounte/', include('accounte.urls')),
    path('accounte/', include('django.contrib.auth.urls')),
    # path('', views.blog.blog, name='blog'),
    path('accounts/', include('allauth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog'))
    # url(r'^blog/', include(blog_urls, namespace='blog')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hanuiproject/blog/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

# class Category(models.Model):
#     name = models.CharField(max_length=250)
#     slug = models.SlugField(max_length=250, unique=True)

#     class Meta:
#         ordering = ('name',)
#         verbose_name = 'category'
#         verbose_name_plural = 'categories'

#     def __str__(self):
#         return self.name

class Category(models.Model):
    class Meta:
        verbose_name = u'분류'
        ordering = ['name']

    name = models.CharField(verbose_name=u'이름', max_length=50)

    def __unicode__(self):
        return self.name

    objects = models.Manager()


class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()
    category = models.ForeignKey(Category, on_delete = "set null", verbose_name=u'분류', null=True, blank=True)

    def __str__(self):
        return self.title
    
    objects = models.Manager()
    #오 이거 넣으니까 해결 됐네

    def summary(self):
        return self.body[:100] #pylint: disable=E1136

    

    # def get_cat_list(self):           #for now ignore this instance method,
    #     k = self.category
    #     breadcrumb = ["dummy"]
    #     while k is not None:
    #         breadcrumb.append(k.slug)
    #         k = k.parent

    #     for i in range(len(breadcrumb)-1):
    #         breadcrumb[i] = '/'.join(breadcrumb[-1:i-1:-1])
    #     return breadcrumb[-1:0:-1]



    

hanuiproject/blog/forms.py
from django import forms
from django.forms import ModelForm, Select, ModelChoiceField
from .models import Blog, Category


class BlogPost(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body']
        category = forms.ChoiceField(widget=forms.Select(),
                              required=True)

# category = forms.ModelChoiceField(queryset=Category.objects.all())

# class Category(forms.ModelForm):
#     class Meta:
#         model = Category
#         widgets = { 'name': Select() }
# class MatchForm(forms.Form):
#     category = forms.ChoiceField(choices = [])

#     def __init__(self, *args, **kwargs):
#         super(MatchForm, self).__init__(*args, **kwargs)
#         self.fields['category'].choices = [(x.pk, x.get_name()) for x in Category.objects.all()]

#email = forms.EmailField()
# fiels = forms.FileField()
# url = forms.URLField()
# words = forms.CharField(max_length = 200)
# max_number = forms.ChoiceField(choices=[{'1','one'}, {'2','two'},{'3','three'}])

hanuiproject/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Blog
from .models import Blog, Category
#model 사용하겠다는 거 알려줘야 함
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import BlogPost
from django.db.models import Q
from django.template import RequestContext
from django.views.generic import ListView, DetailView, CreateView
# from django.views.generic import ListView
# from example.config import pagination



def blog(request):
    blogs = Blog.objects
    #모델로부터 받아 처리할 수 있게끔
    #쿼리셋(을 기능적으로 처리하게 해주는 방법 --> 메소드)
    #모델이름.쿼리셋(objects).메소드()
    blog_list = Blog.objects.all() #블로그 모든 글들을 대상으로
    paginator = Paginator(blog_list, 3) #블로그 객체 세개를 한 페이지로 자르기
    page = request.GET.get('page') #request된 페이지가 뭔지를 알아내고
    try:
        posts = paginator.page(page) #request된 페이지(page변수)를 얻어온 뒤 return해 준다.
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    categories = Category.objects.all()
    return render(request, 'blog.html', {'blogs' : blogs, 'posts' : posts, 'categories' : categories})

def detail(request, blog_id, self):
    blog_detail = get_object_or_404(Blog, pk=blog_id)
    blog_list = Blog.objects.all()
    queryset = super(blog_list, self).get_queryset()
    category_id = self.request.GET.get('category')
    if category_id:
        queryset = queryset.filter(category=category_id)
    return render(request, 'blog/detail.html', {'blog': blog_detail, 'queryset' : queryset})

def new(request):
    # Category = Category.objects.all()
    return render(request, 'blog/new.html')

def create(request):
    blog = Blog()
    blog.title = request.GET['title']
    blog.body = request.GET['body']
    blog.pub_date = timezone.datetime.now()
    blog.save()
    category = Category()
    category.name = request.GET['name']
    category.save()
    return redirect('/blog/' + str(blog.id)) #pylint: disable=E1101
    # render가 '요청이 들어오면 이 html 파일을 보여줘 라는 녀석'이였다면, redirect는 '요청을 들어오면 저쪽 url로 보내버려' 하는 녀석

def blogpost(request):
    #1. 입력된 내용을 처리하는 기능

    if request.method == 'POST' :
        form = BlogPost(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date = timezone.now()
            post.save()
            return redirect('blog:blog')

    #2. 빈 페이지를 띄워주는 기능
    else:
        form = BlogPost()
        return render(request, 'blog/new.html', {'form':form})


    # model = Blog
def search(request):
    template = 'blog/post_list.html'
    # blog_search_results = get_object_or_404(Blog, pk=blog_id)
    query = request.GET.get('q')
    if query:
            results = Blog.objects.filter(Q(title__icontains=query) | Q(body__icontains=query))
    else:
            results = Blog.objects.all()
    
    # pages = pagination(request, results, num=1)
    paginator = Paginator(results, 2) #블로그 객체 세개를 한 페이지로 자르기
    page = request.GET.get('page') #request된 페이지가 뭔지를 알아내고
    try:
        posts = paginator.page(page) #request된 페이지(page변수)를 얻어온 뒤 return해 준다.
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    context = {
        'results' : results,
        # 'page_range' : posts[1],
        'query' : query,
        'posts' : posts,
    }
    return render(request, template, context)

def me(request) :
    return render(request, 'blog/me.html')


def get_context_data(self, **kwargs):
    blog_list = Blog.objects.all()
    context = super(blog_list, self).get_context_data(**kwargs)
    categories = Category.objects.all()
    context['categories'] = categories
    return context

def get_queryset(self):
    blog_list = Blog.objects.all()
    queryset = super(blog_list, self).get_queryset()
    category_id = self.request.GET.get('category')
    if category_id:
        queryset = queryset.filter(category=category_id)
    return queryset

# class PostCategory(ListView):
#     model = Blog
#     template_name = 'blog/blog_category_list.html'
#     def get_queryset(self):
#         category = get_object_or_404(Category, pk=self.kwargs['pk'])
#         return Blog.objects.filter(category=self.category)

#     def get_context_data(self, **kwargs):
#         context = super(PostCategory, self).get_context_data(**kwargs)
#         context['category'] = self.category
#         return context

# class IndexView(ListView):
#     # template_name = 'blog/post_list.html'
    
#     model = Blog
#     context_object_name = 'all_posts'
#     template = 'blog/post_list.html'
#     def search(self):
#         queryset_list = Blog.objects.all()
#         query = self.request.GET.get("q")
#         if query:
#             queryset_list = queryset_list.filter(
#                     Q(title__icontains=query) |
#                     Q(body__icontains=query)
#                     ).distinct()

#         paginator = Paginator(queryset_list, 5)  # Show 5 contacts per page
#         page = self.request.GET.get('page')
#         try:
#             queryset_list = paginator.page(page)
#         except PageNotAnInteger:
#             # If page is not an integer, deliver first page.
#             queryset_list = paginator.page(1)
#         except EmptyPage:
#             # If page is out of range (e.g. 999), deliver last page of results.
#             queryset_list = paginator.page(paginator.num_pages)

hanuiproject/blog/templates/base.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/hanna.css">
    <link rel="stylesheet" href="//cdn.rawgit.com/hiun/NanumSquare/master/nanumsquare.css">

    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/blog-post.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    
    
    <style>
    a, p { font-size: 1em;
    font-family: 'Nanum Square';
    }

    h4 {font-family: 'Nanum Square';}
    .flex {
    display: flex;
    justify-content: space-between;
    }

    .cell.right { text-align : right;}
    
    .detail_container {
    border: 2px;
    }
    h1 {
    font-family: 'Hanna', sans-serif;
    font-size: 48px;
    color: burlywood;
    }

    h2 {
        font-family: 'Nanum Square', bold ;
        font-size: 30px;
        color:lightcoral;
    }

    a.hover {
    text-decoration-color:lightyellow;
    text-decoration: none;
    }

    .container {
        padding: 30px;
        border:lightyellow;
    }
    .center {
    text-align: center;
    }

    .pagination {
    display: inline-block;
    }

    .pagination a {
    color: black;
    float: left;
    padding: 8px 16px;
    text-decoration: none;
    }

    .pagination a.active {
    background-color: plum;
    color: white;
    }

    .pagination a:hover:not(.active) {background-color: #ddd;}

    </style>
</head>
{% load staticfiles %}
<body>
        
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'blog:blog' %}">Hanui</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'blog:blog' %}">Blog <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'blog:newblog' %}">Write</a>

            
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">환영합니다. {{ user.username }} 님!</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'blog:new' %}">글쓰기</a>
                    <a class="dropdown-item" href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
                    <form id="logout" method="POST" action="{% url 'logout' %}">
                        {% csrf_token %} <input type="hidden" />
                    </form>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-item nav-link" href="{% url 'signup' %}">회원가입</a>
            </li>
            <li class="nav-item">
                <a class="nav-item nav-link" href="{% url 'login' %}">로그인</a>
            </li>
            {% endif %}
          </div>
        </div>
      </nav>

      

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

hanuiproject/blog/templates/blog.html
{% extends 'base.html' %}

{% block content %}
<br>


<!-- <head>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">



</head> -->



  <!-- Navigation
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav> -->

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
      <div class="flex">
        <h1 class="mt-4">표현하는 블로그</h1>

        <!-- Author -->
        <p class="lead">
          <br>
          <br>
          <br>
          by
          <a right href="/blog/me/">김하은</a>
        </p>
      </div>

<!-- 

        Preview Image
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt=""> -->

        <hr>

        <!-- Post Content -->
        {% for blog in posts %}
        <div class="container">
            <div class= "flex">
              <a href="{% url 'blog:detail' blog.id %}" style="text-decoration : none" class="left">
                  <h2>{{ blog.title }}</h1>
              </a>
              <p class="right"><br>{{ blog.pub_date }}</p>
            </div>
            <p>{{ blog.summary }}<a href="{% url 'blog:detail' blog.id %}">...more</a></p>
        </div>
        {% endfor %}
        {% include 'blog/paginator.html' with page=posts %}
        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>

        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h4 class="card-header">검색</h4>
          <div class="card-body">
            <form method="GET" action="{% url 'blog:search' %}">
            <div class="input-group">
              <input name="q" value="{{request.GET.q}}" placeholder="..." type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="submit">Go!</button>
            </form>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="right">
                    
                        {% for category in categories %}
                            <!-- <li>{{ category.name }}</li> -->
                            <li>
                                <a href="{% url 'blog:blog' %}?category={{ category.id }}">
                                    {{ category.name }}
                                </a>
                            </li>
                        {% endfor %}
                    
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>



<br>

      <!-- First Previous 3of4 Next Last -->
      <!-- <div class="container">

          {% if posts.has_previous%}
            <a href="?page=1">First</a>
            <a href="?page={{posts.previous_page_number}}{% if query %}&q={{query}}{% endif %}">Previous</a>
          {%endif%}

          <span>{{posts.number}}</span>
          <span>of</span>
          <span>{{posts.paginator.num_pages}}</span>

        {% if posts.has_next %}
            <a href="?page={{posts.next_page_number}}{% if query %}&q={{query}}{% endif %}">Next</a>
            <a href="?page={{posts.paginator.num_page}}{% if query %}&q={{query}}{% endif %}">Last</a>
        {%endif%}
    </div> -->
</body>
</html>
{% endblock %}